apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meal-plan-ingress
spec:
  rules:
    - host: meal-plan.avohome
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: meal-plan-server
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meal-plan-server
spec:
  selector:
    app: meal-plan-server
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-plan-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-plan-server
  template:
    metadata:
      labels:
        app: meal-plan-server
    spec:
      containers:
        - name: app
          image: registry.avohome/meal-plan
          command: ["bun"]
          args: ["run", "server"]
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: meal-plan-scrape-recipe-worker
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meal-plan-scrape-recipe-worker
              image: registry.avohome/meal-plan
              imagePullPolicy: Always
              command: ["bun"]
              args: ["run", "src/scripts/crawlRecipes.ts", "100"]
              env:
                - name: HOST
                  value: "async"
                - name: RECIPES_PER_BATCH
                  value: n100
          restartPolicy: Never
---
# to run a single instance use
# kubectl create job --from=cronjob/create-habit-progress <sync-name/>
apiVersion: batch/v1
kind: CronJob
metadata:
  name: meal-plan-daily-scrape
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meal-plan-daily-scrape
              image: registry.avohome/meal-plan
              imagePullPolicy: Always
              command: ["bun"]
              args: ["run", "src/scripts/dailyGallleryScrape.ts"]
              env:
                - name: HOST
                  value: "async"
          restartPolicy: Never
